### ISSUE TITLE
Changing the pixel rate does not work on Sailfish X (Sony xperia X)

### ISSUE THREAD

**Issue by Frzifus** [fravaccaro/themepacksupport-sailfishos#2]
Anyone an idea what it might be, or how i can change it by hand?

read:
`[nemo@Sailfish ~]$ dconf read /desktop/sailfish/silica/theme_pixel_ratio
1.75`

write:
`[root@Sailfish nemo]# dconf write /desktop/sailfish/silica/theme_pixel_ratio 1.35
error: The operation attempted to modify one or more non-writable keys
Usage:
  dconf write KEY VALUE`

**Comment by Frzifus** [comment]
after “dconf update” worked for me!

**Comment by fravaccaro** [comment]
I'm investigating the issue.

**Comment by Frzifus** [comment]
try this:
https://gist.github.com/Frzifus/7cbeea9d7c15fa9607711c23e7e16c4e

**Comment by fravaccaro** [comment]
Added to Theme pack support 0.5.6.

**Comment by Frzifus** [comment]
after the update to the new version 2.1.4.13 it doesn't work again.

**Comment by fravaccaro** [comment]
Have you tried reinstalling themepacksupport/UI Themer?
