### ISSUE TITLE
Icon size should also be changed on Jolla C

### ISSUE THREAD

**Issue by ksiazkowicz** [fravaccaro/themepacksupport-sailfishos#3]
As seen here:
https://github.com/ksiazkowicz/sailfish-annoyances/blob/master/set_dpi_100.sh
https://github.com/ksiazkowicz/sailfish-annoyances/blob/master/reset_dpi.sh

Otherwise launcher icons are not being resized.

**Comment by fravaccaro** [comment]
Released in v0.7.1.

Thanks for contributing :)
